Ext.define("TDK.SYNCHRONIZE.sync_doc_sa.dokumen_detail.dokumen_detail_sp_sa", {
  extend: "Ext.form.Panel",
  alias: "widget.dokumen_detail_sp_sa",
  reference: "dokumen_detail_sp_sa",
  frame: false,
  border: true,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  fieldDefaults: {
    labelAlign: "left",
    labelWidth: 90,
    margin: "0 10 5 0",
  },
  items: [
    {
      xtype: "grid",
      pid: "GRIDdokumen_detail_sp_sa",
      emptyText: "No Matching Records",
      autoScroll: true,
      flex: 1,
      store: {
        autoLoad: true,
        remoteSort: false,
        remoteFilter: false,
        pageSize: 0,
        proxy: {
          type: "ajax",
          disableCaching: false,
          noCache: false,
          headers: { Authorization: "Bearer " + localStorage.getItem("ST_NJC_JWT") },
          actionMethods: { read: "POST" },
          url: vconfig.service_api + "sync_doc_sa/sync_doc_sas",
          extraParams: {
            method: "read_sp_sa",
          },
          reader: {
            type: "json",
            rootProperty: "Rows",
            totalProperty: "TotalRows",
            successProperty: "success",
          },
        },
        listeners: {
          beforeload: function (store, operation, eOpts) {
            try {
              var GRID = Ext.ComponentQuery.query("sync_doc_sa GRIDsync_doc_sa grid[pid=GRIDsync_doc_sa]")[0];
              var vdt = GRID.getSelectionModel().getSelection()[0].data;
              operation.setParams({
                INVOICE_NO: vdt.INVOICE_NO,
                SA_NO: vdt.SA_NO,
                CONTAINER_NO: vdt.CONTAINER_NO,
              });
            } catch (ex) {
              COMP.TipToast.toast("Error", ex.message, { cls: "danger", delay: 2000 });
            }
          },
        },
      },
      plugins: ["filterfield"],
      viewConfig: {
        enableTextSelection: true,
      },
      columns: [
        { xtype: "rownumberer", width: 40 },
        {
          xtype: "actioncolumn",
          width: 35,
          align: "center",
          menuDisabled: true,
          sortable: false,
          items: [
            {
              icon: vconfig.getstyle + "icon/grid.png",
              handler: "btdetail_rows_click",
              tooltip: "Detail Dokumen",
            },
          ],
        },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SANo", dataIndex: "SANo" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETDPEMI", dataIndex: "ETDPEMI" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ShippingType", dataIndex: "ShippingType" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ToDescription", dataIndex: "ToDescription" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "AttnDescription", dataIndex: "AttnDescription" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FromDescription", dataIndex: "FromDescription" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Ref", dataIndex: "Ref" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SADate", dataIndex: "SADate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PAGE", dataIndex: "PAGE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Cc1", dataIndex: "Cc1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Cc2", dataIndex: "Cc2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Cc3", dataIndex: "Cc3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Cc4", dataIndex: "Cc4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "BLNo", dataIndex: "BLNo" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "MAWBNo", dataIndex: "MAWBNo" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "HAWBNo", dataIndex: "HAWBNo" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FromSchedule1", dataIndex: "FromSchedule1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ToSchedule1", dataIndex: "ToSchedule1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETD1", dataIndex: "ETD1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETA1", dataIndex: "ETA1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Vessel1", dataIndex: "Vessel1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FromSchedule2", dataIndex: "FromSchedule2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ToSchedule2", dataIndex: "ToSchedule2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETD2", dataIndex: "ETD2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETA2", dataIndex: "ETA2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Vessel2", dataIndex: "Vessel2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FromSchedule3", dataIndex: "FromSchedule3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ToSchedule3", dataIndex: "ToSchedule3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETD3", dataIndex: "ETD3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETA3", dataIndex: "ETA3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Vessel3", dataIndex: "Vessel3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FromSchedule4", dataIndex: "FromSchedule4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ToSchedule4", dataIndex: "ToSchedule4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETD4", dataIndex: "ETD4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETA4", dataIndex: "ETA4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Vessel4", dataIndex: "Vessel4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Copy1", dataIndex: "Copy1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Copy2", dataIndex: "Copy2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Copy3", dataIndex: "Copy3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Copy4", dataIndex: "Copy4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PEBNo", dataIndex: "PEBNo" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PEBDate", dataIndex: "PEBDate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_KEMASAN", dataIndex: "KD_KEMASAN" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_KEMASAN", dataIndex: "KET_KEMASAN" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "NO_SEGEL", dataIndex: "NO_SEGEL" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "JNS_SEGEL", dataIndex: "JNS_SEGEL" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Remark1", dataIndex: "Remark1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Remark2", dataIndex: "Remark2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Remark3", dataIndex: "Remark3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "Remark4", dataIndex: "Remark4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KOTA", dataIndex: "KOTA" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_CETAK", dataIndex: "TGL_CETAK" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PEMBERITAHU", dataIndex: "PEMBERITAHU" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_ANGKUT", dataIndex: "KD_ANGKUT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_ANGKUT", dataIndex: "KET_ANGKUT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SHIP_LINE", dataIndex: "SHIP_LINE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "NM_PENGANGKUT", dataIndex: "NM_PENGANGKUT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_EKSPOR", dataIndex: "TGL_EKSPOR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_PELMUAT", dataIndex: "KD_PELMUAT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_PELMUAT", dataIndex: "KET_PELMUAT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_PELBONGKAR", dataIndex: "KD_PELBONGKAR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_PELBONGKAR", dataIndex: "KET_PELBONGKAR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_PELTRANSIT", dataIndex: "KD_PELTRANSIT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_PELTRANSIT", dataIndex: "KET_PELTRANSIT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "NO_LPSE", dataIndex: "NO_LPSE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_LPSE", dataIndex: "TGL_LPSE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_ASAL", dataIndex: "KD_ASAL" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_ASAL", dataIndex: "KET_ASAL" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_TUJUAN", dataIndex: "KD_TUJUAN" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_TUJUAN", dataIndex: "KET_TUJUAN" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_DELIVERY", dataIndex: "KD_DELIVERY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CARA_DELIVERY", dataIndex: "CARA_DELIVERY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_VALUTA", dataIndex: "KD_VALUTA" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_VALUTA", dataIndex: "KET_VALUTA" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_KEMBALI", dataIndex: "TGL_KEMBALI" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TERLAMPIR", dataIndex: "TERLAMPIR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CUST_CODE", dataIndex: "CUST_CODE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "INV_NO", dataIndex: "INV_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOY_NO", dataIndex: "VOY_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FREIGHT", dataIndex: "FREIGHT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_VALUTA_FR", dataIndex: "KET_VALUTA_FR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CYRVC", dataIndex: "CYRVC" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "AmountAWB", dataIndex: "AmountAWB" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "GrossKGSAWB", dataIndex: "GrossKGSAWB" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "AgentCode", dataIndex: "AgentCode" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOY_NO1", dataIndex: "VOY_NO1" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOY_NO2", dataIndex: "VOY_NO2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOY_NO3", dataIndex: "VOY_NO3" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOY_NO4", dataIndex: "VOY_NO4" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_PELMUAT2", dataIndex: "KD_PELMUAT2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_PELMUAT2", dataIndex: "KET_PELMUAT2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_PELBONGKAR2", dataIndex: "KD_PELBONGKAR2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_PELBONGKAR2", dataIndex: "KET_PELBONGKAR2" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KD_ANGKUT_PEB", dataIndex: "KD_ANGKUT_PEB" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "KET_ANGKUT_PEB", dataIndex: "KET_ANGKUT_PEB" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_EKSPOR_PEB", dataIndex: "TGL_EKSPOR_PEB" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "NM_PENGANGKUT_PEB", dataIndex: "NM_PENGANGKUT_PEB" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "NO_BC23", dataIndex: "NO_BC23" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_BC23", dataIndex: "TGL_BC23" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TGL_KEMBALI_BC23", dataIndex: "TGL_KEMBALI_BC23" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "BOOKING_NO", dataIndex: "BOOKING_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TIME", dataIndex: "TIME" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ContainerNo", dataIndex: "ContainerNo" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "RegisterUser", dataIndex: "RegisterUser" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "RegisterDate", dataIndex: "RegisterDate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "UpdateUser", dataIndex: "UpdateUser" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "UpdateDate", dataIndex: "UpdateDate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SAPTransferDate", dataIndex: "SAPTransferDate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SAPTransferStatus", dataIndex: "SAPTransferStatus" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "OracleTransferDate", dataIndex: "OracleTransferDate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "OracleTransferStatus", dataIndex: "OracleTransferStatus" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "OracleBCTransferDate", dataIndex: "OracleBCTransferDate" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "OracleBCTransferStatus", dataIndex: "OracleBCTransferStatus" },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
    },
  ],
  dockedItems: [
    {
      xtype: "toolbar",
      height: 30,
      dock: "top",
      items: ["-"],
      // other options....
    },
  ],
});
