var mainpanel = Ext.ComponentQuery.query("mainpage")[0];
Ext.define("NJC.EXIM.bcout_25.FRMbcout_25_item_detail", {
  extend: "Ext.window.Window",
  alias: "widget.FRMbcout_25_item_detail",
  reference: "FRMbcout_25_item_detail",
  title: "Data Detail Barang",
  modal: true,
  closeAction: "destroy",
  centered: true,
  autoScroll: false,
  controller: "Cbcout_25",
  //y: -110,
  bodyPadding: "5 5 5 5",
  width: mainpanel.getWidth() * 0.9,
  height: mainpanel.getHeight() * 0.8,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  bodyStyle: "background:#FFFFFF;background-color:#FFFFFF",      

        items: [
        { xtype: "textfield", labelWidth: 100, width: 100, fieldLabel: "Status", name: "", fieldCls: "fieldlock", readOnly: true },
        { xtype: "tbspacer", height: 10 },
        {
            
            xtype: "container",
            layout: { type: "vbox", pack: "start", align: "stretch" },
            items: [
            {
                xtype: "fieldset",
                layout: "hbox",
                width: 600,
                bodyPadding: "5 0 0 0",
                items: [
                {
                    xtype: "container",
                    layout: "vbox",
                    margin: "5 0 0 0",
                    items: [
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 150, fieldLabel: "Detail Ke", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 50, width: 100, fieldLabel: "Dari", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 65 },
                        { xtype: "textfield", labelWidth: 100, width: 150, fieldLabel: "Kategori Barang", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", width: 100, value:"Hasil Produksi", name: "KODE_HARGANAME", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 150, fieldLabel: "Penggunaan", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 150, value:"Barang Hasil Olahan", name: "", readOnly: true },
                        { xtype: "tbspacer", width: 56 },
                        { xtype: "textfield", labelWidth: 100, width: 150, fieldLabel: "Kondisi Barang", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 150, value:"TIDAK RUSAK", name: "", readOnly: true },
                        { xtype: "tbspacer", width: 50 },
                        { xtype: "textfield", labelWidth: 100, width: 150, fieldLabel: "Jangka Waktu", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 5 },
                        { xtype: "displayfield", labelWidth: 100, width: 150, value: ">4 tahun", name: "", readOnly: true},
                        ],
                    },
                    ],
                },
                ],
            },
            {
                xtype: "fieldset",
                layout: "hbox",
                title: "DATA BARANG BC 2.5",
                width: 600,
                bodyPadding: "5 0 0 0",
                items: [
                {
                    xtype: "container",
                    layout: "vbox",
                    margin: "5 0 0 0",
                    items: [
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Kode", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Nomor HS", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 65 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Negara Asal", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "label", labelWidth: 100, width: 150, text: "Label", name: "", fieldCls: "fieldinput", readOnly: true, margins: '50 10 10 0'},
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 1085, fieldLabel: "Penggunaan", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Tipe", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Ukuran", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 65 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Spf Lain", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Merk Lain", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    ],
                },
                ],
            },
            {
                xtype: "fieldset",
                layout: "hbox",
                title: "SATUAN & HARGA",
                width: 600,
                //bodyPadding: "0 0 0 0",
                items: [
                {
                    xtype: "container",
                    layout: "vbox",
                    margin: "5 0 0 0",
                    items: [
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Jumlah Satuan", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Jumlah Kemasan", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 65 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Nilai CIF", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 185, fieldLabel: "Jenis Satuan", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "SET", name: "", readOnly: true,},
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width: 185, fieldLabel: "Jenis Kemasan", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "Label", name: "", readOnly: true,},
                        { xtype: "tbspacer", width: 65 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "CIF Rupiah", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Netto (Kgm)", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Volume (M3)", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 65 },
                        { xtype: "textfield", labelWidth: 100, width: 250, fieldLabel: "Harga Penyerahan Rp", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    ],
                },
                ],
            },
            {
                xtype: "container",
                layout: "hbox",
                flex: 1,
                items: [
                {
                    xtype: "fieldset",
                    title: "TARIF & FASILITAS",
                    layout: "vbox",
                    flex: 1,
                    height: 400,
                    bodyPadding: "5 0 0 0",
                    items: [
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 150,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        {
                            xtype: "button",
                            pid: "btinput_bea_masuk_tambahan",
                            text: "O",
                            module: "",
                            tooltip: "Bea Masuk Tambahan",
                        },
                        { xtype: "tbspacer", width: 10 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 150,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width:75, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "%", name: "", readOnly: true,},
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        margin: "5 0 0 0",
                        items: [
                        { xtype: "tbspacer", width: 225 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 200,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 0, width:70, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "%", name: "", readOnly: true,},
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width:175, fieldLabel: "PPN", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 20, value: "%", name: "", readOnly: true,},
                        { xtype: "tbspacer", width: 20 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 200,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 0, width:70, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "%", name: "", readOnly: true,},
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width:175, fieldLabel: "PPnBM", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 20, text: "%", name: "", readOnly: true,},
                        { xtype: "tbspacer", width: 20 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 200,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 0, width:70, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "%", name: "", readOnly: true,},
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width:175, fieldLabel: "PPh", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 20, value: "%", name: "", readOnly: true,},
                        { xtype: "tbspacer", width: 20 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 200,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 0, width:70, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "%", name: "", readOnly: true,},
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "Cukai",
                            labelWidth: 100,
                            width: 425,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "tbspacer", width: 105 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 150,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 100, width:150, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 10, width: 10, value: "%", name: "", readOnly: true,},
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 0, width:60, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 100, width:210, fieldLabel: "Jumlah Satuan", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        {
                            xtype: "combobox",
                            name: "",
                            fieldLabel: "",
                            labelWidth: 0,
                            width: 205,
                            displayField: "",
                            valueField: "",
                            fieldCls: "fieldinput",
                            allowBlank: false,
                            queryMode: "local",
                            forceSelection: true,
                            typeAhead: true,
                            minChars: 0,
                            anyMatch: true,
                            value: "23",
                            store: new Ext.data.Store({
                            data: [
                                { DEFCODE: "1", DEFNAME: "TEST" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                            }),
                        },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "textfield", labelWidth: 0, width:70, fieldLabel: "", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 10 },
                        { xtype: "displayfield", labelWidth: 50, width: 55, value: "%", name: "", readOnly: true,},
                        ],
                    },
                    ],
                },
                { xtype: "container", height: 10 },
                {
                    xtype: "fieldset",
                    title: "FASILITAS & SKEMA TARIF",
                    layout: "vbox",
                    flex: 1,
                    height: 400,
                    items: [
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                        { xtype: "textfield", labelWidth: 60, width: 150, fieldLabel: "Fasilitas", name: "", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "tbspacer", width: 30 },
                        { xtype: "textfield", labelWidth: 60, width: 150, fieldLabel: "Skm Trf", name: "", fieldCls: "fieldinput", readOnly: true },
                        ],
                    },
                    { xtype: "container", height: 10 },
                    {
                        xtype: "container",
                        layout: "hbox",
                        items: [
                            {
                            xtype: "grid",
                            pid: "GRIDbcout_25_input_dokumen",
                            emptyText: "No Matching Records",
                            width: 600,
                            height: 230,
                            plugins: ["filterfield", { ptype: "cellediting", clicksToEdit: 1 }],
                            viewConfig: {
                                enableTextSelection: true,
                            },
                            store: {
                                autoLoad: false,
                                autoSync: false,
                                remoteSort: false,
                                remoteFilter: false,
                                proxy: {
                                type: "localstorage",
                                },
                            },
                            columns: [
                                { xtype: "rownumberer", width: 40 },
                                { header: "KODE", dataIndex: "KODE_JENIS_DOKUMEN", sortable: true, width: 50, filter: { xtype: "textfield" } },
                                {
                                header: "NOMOR",
                                dataIndex: "NOMOR_DOKUMEN",
                                sortable: true,
                                width: 150,
                                filter: { xtype: "textfield" },
                                editor: {
                                    xtype: "textfield",
                                    allowBlank: false,
                                },
                                },
                                {
                                header: "TGL",
                                dataIndex: "TANGGAL_DOKUMEN",
                                sortable: true,
                                width: 90,
                                filter: { xtype: "textfield" },
                                editor: {
                                    xtype: "datefield",
                                    allowBlank: false,
                                    format: "Y-m-d",
                                },
                                renderer: function (val) {
                                    return moment(val).format("YYYY-MM-DD");
                                },
                                },
                                { header: "URAIAN", dataIndex: "URAIAN_DOKUMEN", sortable: true, flex: 1, filter: { xtype: "textfield" } },
                                {
                                xtype: "actioncolumn",
                                width: 25,
                                menuDisabled: true,
                                sortable: false,
                                items: [
                                    {
                                    icon: vconfig.getstyle + "icon/delete.ico",
                                    handler: function (grid, rowIndex, colIndex) {
                                        grid.getSelectionModel().select(rowIndex);
                                        var vdt = grid.getSelectionModel().getSelection()[0].data;
                                        console.log(vdt.KODE_JENIS_DOKUMEN);
                                        if (vdt.KODE_JENIS_DOKUMEN !== "740" || vdt.KODE_JENIS_DOKUMEN !== "741" || vdt.KODE_JENIS_DOKUMEN !== "704" || vdt.KODE_JENIS_DOKUMEN !== "705") {
                                        console.log("hasil hapus");
                                        grid.getStore().removeAt(rowIndex);
                                        }
                                    },
                                    },
                                ],
                                },
                            ],
                            listeners: {
                                beforeedit: function (grid, e) {
                                if (e.record.data.KODE_JENIS_DOKUMEN === "740" || e.record.data.KODE_JENIS_DOKUMEN === "741" || e.record.data.KODE_JENIS_DOKUMEN === "704" || e.record.data.KODE_JENIS_DOKUMEN === "705") {
                                    e.cancel = true;
                                }
                                },
                            },
                            tbar: [
                                {
                                xtype: "button",
                                pid: "btedit_dokumen_item_detail",
                                text: "Edit Dokumen",
                                module: "module_input_dokumen",
                                icon: vconfig.getstyle + "icon/new.ico",
                                tooltip: "Edit Dokumen",
                                },
                            ],
                            },
                        ],
                    },
                    { xtype: "tbspacer", height: 10 },
                    { xtype: "label", labelWidth: 60, width: 150, text: "Bahan Baku"},
                    { xtype: "tbspacer", height: 10 },
                    {xtype: "textfield", labelWidth: 100, width: 200, fieldLabel: "Jumlah Bahan Baku", name: "", fieldCls: "fieldinput", readOnly: true },
                        
                    ],
                },
                ],
            },
            
            
            ],
        },
        { xtype: "tbspacer", height: 5 },
        ],
        dockedItems: [
            {
              xtype: "toolbar",
              height: 30,
              dock: "top",
              items: ["-", { xtype: "button", pid: "btsavedokumendraft", text: "Simpan Dokumen Draft", icon: vconfig.getstyle + "icon/save.ico", tooltip: "Simpan Dokumen Draft" }],
              // other options....
            },
          ],
          listeners: {
            afterrender: "",
          },
});
