Ext.define("NJC.MASTERS.master_goods.GRIDmaster_goods", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDmaster_goods",
  reference: "GRIDmaster_goods",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  items: [
    {
      xtype: "grid",
      pid: "GRIDmaster_goods",
      emptyText: "No Matching Records",
      autoScroll: true,
      flex: 1,
      plugins: ["filterfield", "gridexporter"],
      store: "",
      pageSize: 100,
      columns: [
        { xtype: "rownumberer", width: 50 },
        {
          xtype: "actioncolumn",
          width: 35,
          align: "center",
          menuDisabled: true,
          sortable: false,
          items: [
            {
              icon: vconfig.getstyle + "icon/grid.png",
              handler: "btdetail_rows_click",
              tooltip: "Detail Part",
            },
          ],
        },
        { hidden: true, header: "ID", dataIndex: "ID", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "PART NO", dataIndex:"PART_NO", sortable: true, width: 160, filter: { xtype: "textfield" } },
        { header: "PART NO 2", dataIndex:"PART_NO2", sortable: true, width: 160, filter: { xtype: "textfield" } },
        { header: "HS CODE", dataIndex:"HS_CODE", sortable: true, width: 160, filter: { xtype: "textfield" } },
        { header: "BASE PART", dataIndex:"BASE_PART", sortable: true, width: 160, filter: { xtype: "textfield" } },
        { header: "PART ALIAS", dataIndex:"PART_ALIAS", sortable: true, width: 160, filter: { xtype: "textfield" } },
        { header: "PART NAME", dataIndex:"PART_NAME", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "PART DESCRIPTION", dataIndex:"PART_DESCRIPTION", sortable: true, width: 300, filter: { xtype: "textfield" } },
        { header: "PART MIN QTY", dataIndex:"PART_MIN_QTY", renderer: "formatAmount", align: "right", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "PART UOM", dataIndex:"PART_UOM", sortable: true, width: 130, filter: { xtype: "textfield" } },
        { header: "PART GROUP", dataIndex:"PART_GROUP", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "PART CATEGORY", dataIndex:"PART_CATEGORY", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "PART TYPE", dataIndex:"PART_TYPE", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "PART CONSUMABLE", dataIndex:"PART_CONSUMABLE", sortable: true, width: 210, filter: { xtype: "textfield" } },
        { header: "PART SVC LEVEL", dataIndex:"PART_SVC_LEVEL", renderer: "formatAmount", align: "right", sortable: true, width: 220, filter: { xtype: "textfield" } },
        { header: "RACK NO", dataIndex:"RACK_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "IS BOM", dataIndex:"IS_BOM", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "IS PARTLIST", dataIndex:"IS_PARTLIST", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "IS AUTO OUT", dataIndex:"IS_AUTO_OUT", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "ID COMPANY", dataIndex:"ID_COMPANY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CREATE USER", dataIndex:"CREATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CREATE DATE", dataIndex:"CREATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "UPDATE USER", dataIndex:"UPDATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "UPDATE DATE", dataIndex:"UPDATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
    },
  ],
  listeners: {
    afterrender: "GRIDmaster_goods_load",
  },
});
