Ext.define("TDK.INVENTORY.inv_wip_in.GRIDinv_wip_in", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDinv_wip_in",
  reference: "GRIDinv_wip_in",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  // items: [
  //   {
  //     xtype: "grid",
  //     pid: "GRIDinv_wip_in",
  //     emptyText: "No Matching Records",
  //     autoScroll: true,
  //     flex: 1,
  //     plugins: ["filterfield"],
  //     viewConfig: {
  //       enableTextSelection: true,
  //     },
  //     store: {
  //       autoLoad: true,
  //       remoteSort: true,
  //       remoteFilter: true,
  //       pageSize: 17,
  //       proxy: {
  //         type: "ajax",
  //         disableCaching: false,
  //         noCache: false,
  //         headers: { Authorization: "Bearer " + localStorage.getItem("ST_NJC_JWT") },
  //         actionMethods: { read: "POST" },
  //         url: vconfig.service_api + "inv_wip_in/inv_wip_ins",
  //         extraParams: {
  //           method: "read_in",
  //         },
  //         reader: {
  //           type: "json",
  //           rootProperty: "Rows",
  //           totalProperty: "TotalRows",
  //           successProperty: "success",
  //         },
  //       },
  //     },
  //     columns: [
  //       { xtype: "rownumberer", width: 50 },
  //       { header: "IN DATE", dataIndex: "WIN_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
  //       { header: "INVOICE", dataIndex: "INVOICE_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
  //       { header: "MAPPING PART", dataIndex: "MAPP_PARTNO", sortable: true, width: 100, filter: { xtype: "textfield" } },
  //       { header: "PART NAME", dataIndex: "PART_NAME", sortable: true, width: 250, filter: { xtype: "textfield" } },
  //       { header: "QTY", dataIndex: "WIN_QTY", sortable: true, align: "right", renderer: "formatqty", width: 100, filter: { xtype: "textfield" } },
  //       { header: "SOURCE", dataIndex: "SUMBER_DATA", sortable: true, width: 65, filter: { xtype: "textfield" } },
  //       { header: "BC TYPE", dataIndex: "BC_TYPE", sortable: true, width: 65, filter: { xtype: "textfield" } },
  //       { header: "NOMOR AJU", dataIndex: "NOMOR_AJU", sortable: true, width: 170, filter: { xtype: "textfield" } },
  //       { header: "TANGGAL AJU", dataIndex: "TANGGAL_AJU", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "NOMOR DAFTAR", dataIndex: "NOMOR_DAFTAR", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "TANGGAL DAFTAR", dataIndex: "TANGGAL_DAFTAR", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "INPUT", dataIndex: "WIN_INPUT", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //     ],
  //     bbar: {
  //       xtype: "pagingtoolbar",
  //       displayInfo: true,
  //       displayMsg: "Displaying topics {0} - {1} of {2}",
  //       emptyMsg: "No topics to display",
  //     },
  //   },
  // ],
});
