Ext.define("NJC.MASTERS.goods_barang.GRIDgoods_barang", {
    extend: "Ext.form.Panel",
    alias: "widget.GRIDgoods_barang",
    reference: "GRIDgoods_barang",
    frame: false,
    border: false,
    autoScroll: true,
    layout: { type: "vbox", pack: "start", align: "stretch" },
    requires: [],
    items: [
      {
        xtype: "grid",
        pid: "GRIDgoods_barang",
        emptyText: "No Matching Records",
        autoScroll: true,
        flex: 1,
        plugins: ["filterfield", "gridexporter"],
        store: "",
        // store: new Ext.data.Store({
        //   data:[
        //     {
        //       ID:'1',
        //       KODE_INTERNAL:'1',
        //       NAMA:'1',
        //       ALAMAT:'1',
        //       KODE_ID:'1',
        //       KODE_NEGARA:'1',
        //       NPWP:'1',
        //       ID_CEISA:'1',
        //       KODE_COO:'1',
        //       KODE_MOLTS:'1',
        //       KODE_LP:'1',
        //       CREATE_USER:'1',
        //       CREATE_DATE:'1',
        //       UPDATE_USER:'1',
        //       UPDATE_DATE:'1',
        //     }
        //   ],
        //   fields:[
        //     'ID',
        //     'KODE_INTERNAL',
        //     'NAMA',
        //     'ALAMAT',
        //     'KODE_ID',
        //     'KODE_NEGARA',
        //     'NPWP',
        //     'ID_CEISA',
        //     'KODE_COO',
        //     'KODE_MOLTS',
        //     'KODE_LP',
        //     'CREATE_USER',
        //     'CREATE_DATE',
        //     'UPDATE_USER',
        //     'UPDATE_DATE',
        //   ]
        // }),
        columns: [
          { xtype: "rownumberer", width: 50 },
          {
            xtype: "actioncolumn",
            width: 35,
            align: "center",
            menuDisabled: true,
            sortable: false,
            items: [
              {
                icon: vconfig.getstyle + "icon/grid.png",
                handler: "btdetail_rows_click",
                tooltip: "Detail Supplier",
              },
            ],
          },
          { hidden: true, header: "ID", dataIndex: "ID", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "KODE INTERNAL", dataIndex: "KODE_INTERNAL", sortable: true, width: 100, filter: { xtype: "textfield" } },
          { header: "NAMA", dataIndex: "NAMA", sortable: true, width: 300, filter: { xtype: "textfield" } },
          { header: "ALAMAT", dataIndex: "ALAMAT", sortable: true, width: 400, filter: { xtype: "textfield" } },
          { header: "KODE ID", dataIndex: "KODE_ID", sortable: true, width: 80, filter: { xtype: "textfield" } },
          { header: "KODE NEGARA", dataIndex: "KODE_NEGARA", sortable: true, width: 100, filter: { xtype: "textfield" } },
          { header: "NPWP", dataIndex: "NPWP", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "ID CEISA", dataIndex: "ID_CEISA", sortable: true, width: 80, filter: { xtype: "textfield" } },
          { header: "KODE COO", dataIndex: "KODE_COO", sortable: true, width: 80, filter: { xtype: "textfield" } },
          { header: "KODE MOLTS", dataIndex: "KODE_MOLTS", sortable: true, width: 80, filter: { xtype: "textfield" } },
          { header: "KODE LP", dataIndex: "KODE_LP", sortable: true, width: 80, filter: { xtype: "textfield" } },
          { header: "CREATE USER", dataIndex: "CREATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
          { header: "CREATE DATE", dataIndex: "CREATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "UPDATE USER", dataIndex: "UPDATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
          { header: "UPDATE DATE", dataIndex: "UPDATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
        ],
        bbar: {
          xtype: "pagingtoolbar",
          displayInfo: true,
          displayMsg: "Displaying topics {0} - {1} of {2}",
          emptyMsg: "No topics to display",
        },
      },
    ],
    listeners: {
      afterrender: "GRIDgoods_barang_load",
    },
  });
  