Ext.define("TDK.INVENTORY.inv_wnt_out.GRIDinv_wnt_out", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDinv_wnt_out",
  reference: "GRIDinv_wnt_out",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  // items: [
  //   {
  //     xtype: "grid",
  //     pid: "GRIDinv_wnt_out",
  //     emptyText: "No Matching Records",
  //     autoScroll: true,
  //     flex: 1,
  //     plugins: ["filterfield"],
  //     viewConfig: {
  //       enableTextSelection: true,
  //     },
  //     store: {
  //       autoLoad: true,
  //       remoteSort: true,
  //       remoteFilter: true,
  //       pageSize: 17,
  //       proxy: {
  //         type: "ajax",
  //         disableCaching: false,
  //         noCache: false,
  //         headers: { Authorization: "Bearer " + localStorage.getItem("ST_NJC_JWT") },
  //         actionMethods: { read: "POST" },
  //         url: vconfig.service_api + "inv_material_out/inv_material_outs",
  //         extraParams: {
  //           method: "read_out",
  //         },
  //         reader: {
  //           type: "json",
  //           rootProperty: "Rows",
  //           totalProperty: "TotalRows",
  //           successProperty: "success",
  //         },
  //       },
  //     },
  //     columns: [
  //       { xtype: "rownumberer", width: 50 },
  //       { hidden: true, header: "ID", dataIndex: "ID", sortable: true, width: 200, filter: { xtype: "textfield" } },
  //       { header: "OUT NO", dataIndex: "OUT_NO", sortable: true, width: 170, filter: { xtype: "textfield" } },
  //       { header: "OUT DATE", dataIndex: "OUT_DATE", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "KATEGORI", dataIndex: "OUT_KATEGORI", sortable: true, width: 120, filter: { xtype: "textfield" } },
  //       { header: "INVOICE", dataIndex: "INVOICE_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
  //       { header: "PART NO", dataIndex: "PART_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
  //       { header: "MAPPING PART", dataIndex: "MAPP_PARTNO", sortable: true, width: 100, filter: { xtype: "textfield" } },
  //       { header: "PART NAME", dataIndex: "PART_NAME", sortable: true, width: 250, filter: { xtype: "textfield" } },
  //       { header: "QTY", dataIndex: "OUT_QTY", sortable: true, align: "right", renderer: "formatqty", width: 100, filter: { xtype: "textfield" } },
  //       { header: "SOURCE", dataIndex: "SUMBER_DATA", sortable: true, width: 65, filter: { xtype: "textfield" } },
  //       { header: "BC TYPE", dataIndex: "BC_TYPE", sortable: true, width: 65, filter: { xtype: "textfield" } },
  //       { header: "NOMOR AJU", dataIndex: "NOMOR_AJU", sortable: true, width: 170, filter: { xtype: "textfield" } },
  //       { header: "TANGGAL AJU", dataIndex: "TANGGAL_AJU", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "NOMOR DAFTAR", dataIndex: "NOMOR_DAFTAR", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "TANGGAL DAFTAR", dataIndex: "TANGGAL_DAFTAR", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "INPUT", dataIndex: "OUT_INPUT", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //       { header: "USER", dataIndex: "CREATE_USER", sortable: true, width: 80, filter: { xtype: "textfield" } },
  //     ],
  //     bbar: {
  //       xtype: "pagingtoolbar",
  //       displayInfo: true,
  //       displayMsg: "Displaying topics {0} - {1} of {2}",
  //       emptyMsg: "No topics to display",
  //     },
  //   },
  // ],
  // dockedItems: [
  //   {
  //     xtype: "toolbar",
  //     height: 30,
  //     dock: "top",
  //     items: [{ xtype: "button", text: "New Input", pid: "btnew_inv_wnt_out", icon: vconfig.getstyle + "icon/add.png", tooltip: "New" }],
  //     // other options....
  //   },
  // ],
  // listeners: {
  //   afterrender: "GRIDinv_wnt_out_load",
  // },
});
