Ext.define("NJC.MASTERS.mst_item_hs.GRIDmst_item_hs", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDmst_item_hs",
  reference: "GRIDmst_item_hs",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  items: [
    {
      xtype: "grid",
      pid: "GRIDmst_item_hs",
      emptyText: "No Matching Records",
      autoScroll: true,
      flex: 1,
      plugins: ["filterfield", "gridexporter"],
      store: "",
      pageSize: 20,
      columns: [
        { xtype: "rownumberer", width: 50 },
        {
          xtype: "actioncolumn",
          width: 35,
          align: "center",
          menuDisabled: true,
          sortable: false,
          items: [
            {
              icon: vconfig.getstyle + "icon/grid.png",
              handler: "btdetail_rows_click",
              tooltip: "Detail Part HS",
            },
          ],
        },
        { header: "NOMOR HS", dataIndex:"NOMOR_HS", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "TARIF BM", dataIndex:"TARIF_BM", renderer: "formatAmount", align: "right", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "TARIF CUKAI", dataIndex:"TARIF_CUKAI", renderer: "formatAmount", align: "right", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "TARIF PPH", dataIndex:"TARIF_PPH", renderer: "formatAmount", align: "right", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "TARIF PPN", dataIndex:"TARIF_PPN", renderer: "formatAmount", align: "right", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "TARIF PPNBM", dataIndex:"TARIF_PPNBM", renderer: "formatAmount", align: "right", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "ID COMPANY", dataIndex:"ID_COMPANY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CREATE USER", dataIndex:"CREATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CREATE DATE", dataIndex:"CREATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "UPDATE USER", dataIndex:"UPDATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "UPDATE DATE", dataIndex:"UPDATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
    },
  ],
  listeners: {
    afterrender: "GRIDmst_item_hs_load",
  },
});
