Ext.define("TDK.MASTERS.mst_fg_carline.GRIDmst_fg_carline", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDmst_fg_carline",
  reference: "GRIDmst_fg_carline",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  items: [
    {
      xtype: "grid",
      pid: "GRIDmst_fg_carline",
      emptyText: "No Matching Records",
      autoScroll: true,
      flex: 1,
      plugins: ["filterfield", "gridexporter"],
      store: "",
      columns: [
        { xtype: "rownumberer", width: 50 },
        {
          xtype: "actioncolumn",
          width: 35,
          align: "center",
          menuDisabled: true,
          sortable: false,
          items: [
            {
              icon: vconfig.getstyle + "icon/grid.png",
              handler: "btdetail_rows_click",
              tooltip: "Detail Carline",
            },
          ],
        },
        { hidden: true, header: "ID", dataIndex: "ID", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "CARLINE", dataIndex: "CARLINE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CARLINE NAME", dataIndex: "CARLINE_NAME", sortable: true, width: 200, filter: { xtype: "textfield" } },
        { header: "CONTAINER PALLET_QTY", dataIndex: "CONTAINER_PALLET_QTY", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "MIX CLS", dataIndex: "MIX_CLS", sortable: true, width: 60, filter: { xtype: "textfield" } },
        { header: "PREFIX DR", dataIndex: "PREFIX_DR", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "NEW CARLINE", dataIndex: "NEW_CARLINE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "INVOICE CODE", dataIndex: "INVOICE_CODE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "INVOICE CODE SAMPLE", dataIndex: "INVOICE_CODE_SAMPLE", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "INVOICENO SAMPLE PREFIX", dataIndex: "INVOICENO_SAMPLE_PREFIX", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "INVOICENO SAMPLE AF", dataIndex: "INVOICENO_SAMPLE_AF", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "INVOICENO SAMPLE SF", dataIndex: "INVOICENO_SAMPLE_SF", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "INVOICENO PROTOTYPE AF", dataIndex: "INVOICENO_PROTOTYPE_AF", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "INVOICENO PROTOTYPE SF", dataIndex: "INVOICENO_PROTOTYPE_SF", sortable: true, width: 150, filter: { xtype: "textfield" } },
        { header: "INTERNAL ORDER", dataIndex: "INTERNAL_ORDER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CREATE USER", dataIndex: "CREATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CREATE DATE", dataIndex: "CREATE_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "UPDATE USER", dataIndex: "UPDATE_USER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "UPDATE DATE", dataIndex: "UPDATE_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ID COMPANY", dataIndex:"ID_COMPANY", sortable: true, width: 80, filter: { xtype: "textfield" } },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
    },
  ],
  listeners: {
    afterrender: "GRIDmst_fg_carline_load",
  },
});
