Ext.define("TDK.SYNCHRONIZE.sync_doc_molts.sumberdata.GRIDsumberdata", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDsumberdata",
  reference: "GRIDsumberdata",
  frame: false,
  border: true,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  items: [
    {
      xtype: "grid",
      pid: "GRIDsumberdata",
      emptyText: "No Matching Records",
      autoScroll: true,
      title: "",
      flex: 1,
      plugins: ["filterfield", "gridexporter"],
      viewConfig: {
        enableTextSelection: true,
      },
      store: {
        autoLoad: true,
        remoteSort: false,
        remoteFilter: false,
        pageSize: 0,
        proxy: {
          type: "ajax",
          disableCaching: false,
          noCache: false,
          headers: { Authorization: "Bearer " + localStorage.getItem("ST_NJC_JWT") },
          actionMethods: { read: "POST" },
          url: vconfig.service_api + "sync_doc_molts/sync_doc_moltss",
          extraParams: {
            method: "read_original",
            module: "molts",
          },
          reader: {
            type: "json",
            rootProperty: "Rows",
            totalProperty: "TotalRows",
            successProperty: "success",
          },
        },
        listeners: {
          beforeload: function (store, operation, eOpts) {
            try {
              var GRID = Ext.ComponentQuery.query("sync_doc_molts GRIDsync_doc_molts grid[pid=GRIDsync_doc_molts]")[0];
              var vdt = GRID.getSelectionModel().getSelection()[0].data;
              operation.setParams({
                INVOICE_NO: vdt.INVOICE_NO,
              });
            } catch (ex) {
              COMP.TipToast.toast("Error", ex.message, { cls: "danger", delay: 2000 });
            }
          },
        },
      },
      columns: [
        { xtype: "rownumberer", width: 40 },
        { header: "VENDOR", dataIndex: "VENDOR", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "INVOICE_NO", dataIndex: "INVOICE_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CONTAINER_NO", dataIndex: "CONTAINER_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "INVOICE_DATE", dataIndex: "INVOICE_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ETD_VEBDER", dataIndex: "ETD_VEBDER", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ETD_PORT", dataIndex: "ETD_PORT", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ETA_PORT", dataIndex: "ETA_PORT", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ETA_FACT", dataIndex: "ETA_FACT", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "TRANSPORT_WAY", dataIndex: "TRANSPORT_WAY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CARA_BAYAR", dataIndex: "CARA_BAYAR", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ONEROUS", dataIndex: "ONEROUS", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "SHIP_FROM", dataIndex: "SHIP_FROM", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "VIA", dataIndex: "VIA", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "SHIP_TO", dataIndex: "SHIP_TO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "PAY_BY", dataIndex: "PAY_BY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "SEAL_NO", dataIndex: "SEAL_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "SHIP_NAME", dataIndex: "SHIP_NAME", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "SHIP_COMPANY", dataIndex: "SHIP_COMPANY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ORDER_NO", dataIndex: "ORDER_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ITEM_NUMBER", dataIndex: "ITEM_NUMBER", sortable: true, width: 100, filter: { xtype: "textfield" }, tdCls: "fieldinput" },
        { header: "DESCRIPTION", dataIndex: "DESCRIPTION", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "ARRIV_PLAN_NUMBER", dataIndex: "ARRIV_PLAN_NUMBER", sortable: true, width: 100, filter: { xtype: "textfield" }, tdCls: "fieldinput" },
        { header: "UOM", dataIndex: "UOM", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "PRICE", dataIndex: "PRICE", sortable: true, width: 100, filter: { xtype: "textfield" }, tdCls: "fieldinput" },
        { header: "CURRENT_MONEY", dataIndex: "CURRENT_MONEY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CTN_NO_PREFIX", dataIndex: "CTN_NO_PREFIX", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CTN_NO_FROM", dataIndex: "CTN_NO_FROM", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CTN_NO_TO", dataIndex: "CTN_NO_TO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CTN_QUANTITY", dataIndex: "CTN_QUANTITY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "PACKING_QTY", dataIndex: "PACKING_QTY", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "NET_WEIGHT", dataIndex: "NET_WEIGHT", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "GROSS_WEIGHT", dataIndex: "GROSS_WEIGHT", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "WEIGHT_UOM", dataIndex: "WEIGHT_UOM", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "VOLUME", dataIndex: "VOLUME", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "VOLUME_UOM", dataIndex: "VOLUME_UOM", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "BL_DATE", dataIndex: "BL_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "BL_NO", dataIndex: "BL_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "FREIGHT", dataIndex: "FREIGHT", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "EURO_NO", dataIndex: "EURO_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "PALET_NO", dataIndex: "PALET_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "HS_CODE", dataIndex: "HS_CODE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "COUNTRY_OF", dataIndex: "COUNTRY_OF", sortable: true, width: 100, filter: { xtype: "textfield" }, tdCls: "fieldinput" },
        { header: "CAUPRI", dataIndex: "CAUPRI", sortable: true, width: 100, filter: { xtype: "textfield" }, tdCls: "fieldinput" },
        { header: "CATAMZ", dataIndex: "CATAMZ", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "CAROUD", dataIndex: "CAROUD", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "AKHIR", dataIndex: "AKHIR", sortable: true, width: 100, filter: { xtype: "textfield" } },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Total Data {2}",
        emptyMsg: "No topics to display",
      },
    },
  ],
  dockedItems: [
    {
      xtype: "toolbar",
      height: 30,
      dock: "top",
      items: [
        "-",
        "->",
        {
          xtype: "button",
          text: "Download",
          pid: "btsumberdata_download",
          icon: vconfig.getstyle + "icon/excel.ico",
          tooltip: "Download Data",
          handler: "btsumberdata_download",
          cfg: {
            type: "excel07",
            ext: "xlsx",
          },
        },
      ],
      // other options....
    },
  ],
});
