Ext.define("NJC.MASTERS.master_tenant.GRIDmaster_tenant", {
    extend: "Ext.form.Panel",
    alias: "widget.GRIDmaster_tenant",
    reference: "GRIDmaster_tenant",
    frame: false,
    border: false,
    autoScroll: true,
    layout: { type: "vbox", pack: "start", align: "stretch" },
    //requires: [],
    items: [
      {
        xtype: "grid",
        pid: "GRIDmaster_tenant",
        emptyText: "No Matching Records",
        autoScroll: true,
        flex: 1,
        plugins: ["filterfield", "gridexporter"],
        pageSize: 100,
        store: [],
        columns: [
          { xtype: "rownumberer", width: 50 },
          {
            xtype: "actioncolumn",
            width: 35,
            align: "center",
            //menuDisabled: true,
            sortable: false,
            items: [
              {
                icon: vconfig.getstyle + "icon/grid.png",
                handler: "btdetail_rows_click",
                tooltip: "Detail Supplier",
              },
            ],
          },
          { hidden: true, header: "ID", dataIndex: "ID", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "KODE INTERNAL", dataIndex: "KODE_INTERNAL", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "NAMA", dataIndex: "NAMA", sortable: true, width: 300, filter: { xtype: "textfield" } },
          { header: "ALAMAT", dataIndex: "ALAMAT", sortable: true, width: 400, filter: { xtype: "textfield" } },
          { header: "KODE ID", dataIndex: "KODE_ID", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "KODE NEGARA", dataIndex: "KODE_NEGARA", sortable: true, width: 170, filter: { xtype: "textfield" } },
          { header: "NPWP", dataIndex: "NPWP", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "ID CEISA", dataIndex: "ID_CEISA", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "KODE COO", dataIndex: "KODE_COO", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "KODE MOLTS", dataIndex: "KODE_MOLTS", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "KODE LP", dataIndex: "KODE_LP", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "CREATE USER", dataIndex: "CREATE_USER", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "CREATE DATE", dataIndex: "CREATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
          { header: "UPDATE USER", dataIndex: "UPDATE_USER", sortable: true, width: 150, filter: { xtype: "textfield" } },
          { header: "UPDATE DATE", dataIndex: "UPDATE_DATE", sortable: true, width: 200, filter: { xtype: "textfield" } },
        ],
        bbar: {
          xtype: "pagingtoolbar",
          displayInfo: true,
          displayMsg: "Displaying topics {0} - {1} of {2}",
          emptyMsg: "No topics to display",
        },
      },
    ],
    listeners: {
      afterrender: "GRIDmaster_tenant_load",
    },
  });
  