Ext.define("TDK.SYNCHRONIZE.sync_fg_in.GRIDsync_fg_in", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDsync_fg_in",
  reference: "GRIDsync_fg_in",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "hbox", pack: "start", align: "stretch" },
  requires: [],
  items: [
    {
      xtype: "grid",
      pid: "GRIDsync_fg_in",
      emptyText: "No Matching Records",
      autoScroll: true,
      flex: 1,
      plugins: ["filterfield"],
      store: "",
      columns: [
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VENDOR", dataIndex: "VENDOR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "INVOICE_NO", dataIndex: "INVOICE_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CONTAINER_NO", dataIndex: "CONTAINER_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "INVOICE_DATE", dataIndex: "INVOICE_DATE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETD_VEBDER", dataIndex: "ETD_VEBDER" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETD_PORT", dataIndex: "ETD_PORT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETA_PORT", dataIndex: "ETA_PORT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ETA_FACT", dataIndex: "ETA_FACT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "TRANSPORT_WAY", dataIndex: "TRANSPORT_WAY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CARA_BAYAR", dataIndex: "CARA_BAYAR" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ONEROUS", dataIndex: "ONEROUS" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SHIP_FROM", dataIndex: "SHIP_FROM" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VIA", dataIndex: "VIA" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SHIP_TO", dataIndex: "SHIP_TO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PAY_BY", dataIndex: "PAY_BY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SEAL_NO", dataIndex: "SEAL_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SHIP_NAME", dataIndex: "SHIP_NAME" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "SHIP_COMPANY", dataIndex: "SHIP_COMPANY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ORDER_NO", dataIndex: "ORDER_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ITEM_NUMBER", dataIndex: "ITEM_NUMBER" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "DESCRIPTION", dataIndex: "DESCRIPTION" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "ARRIV_PLAN_NUMBER", dataIndex: "ARRIV_PLAN_NUMBER" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "UOM", dataIndex: "UOM" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PRICE", dataIndex: "PRICE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CURRENT_MONEY", dataIndex: "CURRENT_MONEY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CTN_NO_PREFIX", dataIndex: "CTN_NO_PREFIX" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CTN_NO_FROM", dataIndex: "CTN_NO_FROM" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CTN_NO_TO", dataIndex: "CTN_NO_TO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CTN_QUANTITY", dataIndex: "CTN_QUANTITY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PACKING_QTY", dataIndex: "PACKING_QTY" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "NET_WEIGHT", dataIndex: "NET_WEIGHT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "GROSS_WEIGHT", dataIndex: "GROSS_WEIGHT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "WEIGHT_UOM", dataIndex: "WEIGHT_UOM" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOLUME", dataIndex: "VOLUME" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "VOLUME_UOM", dataIndex: "VOLUME_UOM" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "BL_DATE", dataIndex: "BL_DATE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "BL_NO", dataIndex: "BL_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "FREIGHT", dataIndex: "FREIGHT" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "EURO_NO", dataIndex: "EURO_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "PALET_NO", dataIndex: "PALET_NO" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "HS_CODE", dataIndex: "HS_CODE" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "COUNTRY_OF", dataIndex: "COUNTRY_OF" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CAUPRI", dataIndex: "CAUPRI" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CATAMZ", dataIndex: "CATAMZ" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "CAROUD", dataIndex: "CAROUD" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "AKHIR", dataIndex: "AKHIR" },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
      listeners: {
        afterrender: "GRIDsync_fg_in_load",
      },
    },
    { xtype: "tbspacer", width: 5 },
    {
      xtype: "grid",
      pid: "GRIDsync_fg_in_log",
      emptyText: "No Matching Records",
      autoScroll: true,
      width: 550,
      plugins: ["filterfield"],
      store: "",
      columns: [
        { sortable: true, width: 80, filter: { xtype: "textfield" }, header: "STATUS", dataIndex: "LOG_STATUS" },
        { sortable: true, width: 140, filter: { xtype: "textfield" }, header: "DATE SYNC", dataIndex: "LOG_DATE" },
        { sortable: true, width: 300, filter: { xtype: "textfield" }, header: "NAME SYNC", dataIndex: "LOG_FILENAME" },
        { sortable: true, width: 300, filter: { xtype: "textfield" }, header: "DESCRIPTION", dataIndex: "LOG_DESCRIPTION" },
        { sortable: true, width: 100, filter: { xtype: "textfield" }, header: "USER", dataIndex: "LOG_USER" },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
      listeners: {
        afterrender: "GRIDsync_fg_in_log_load",
      },
    },
  ],
});