Ext.define("TDK.INVENTORY.inv_subassy_aw_in.GRIDinv_subassy_aw_in", {
  extend: "Ext.form.Panel",
  alias: "widget.GRIDinv_subassy_aw_in",
  reference: "GRIDinv_subassy_aw_in",
  frame: false,
  border: false,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  items: [
    {
      xtype: "grid",
      pid: "GRIDinv_subassy_aw_in",
      emptyText: "No Matching Records",
      autoScroll: true,
      flex: 1,
      plugins: ["filterfield"],
      viewConfig: {
        enableTextSelection: true,
      },
      store: {
        autoLoad: true,
        remoteSort: true,
        remoteFilter: true,
        pageSize: 17,
        proxy: {
          type: "ajax",
          disableCaching: false,
          noCache: false,
          headers: { Authorization: "Bearer " + localStorage.getItem("ST_NJC_JWT") },
          actionMethods: { read: "POST" },
          url: vconfig.service_api + "inv_subassy_aw_in/inv_subassy_aw_ins",
          extraParams: {
            method: "read_in",
          },
          reader: {
            type: "json",
            rootProperty: "Rows",
            totalProperty: "TotalRows",
            successProperty: "success",
          },
        },
      },
      columns: [
        { xtype: "rownumberer", width: 50 },
        { header: "RECEIPT NO", dataIndex: "RECEIPT_NO", sortable: true, width: 190, filter: { xtype: "textfield" } },
        { header: "RECEIPT DATE", dataIndex: "RECEIPT_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "DOK. NUMBER", dataIndex: "INVOICE_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "PART NO", dataIndex: "PART_NO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "MAPPING PART", dataIndex: "MAPP_PARTNO", sortable: true, width: 100, filter: { xtype: "textfield" } },
        { header: "PART NAME", dataIndex: "PART_NAME", sortable: true, width: 250, filter: { xtype: "textfield" } },
        { header: "SEQ NO", dataIndex: "IS_FROM_AW_SEQNO", sortable: true, width: 55, filter: { xtype: "textfield" } },
        { header: "QTY", dataIndex: "RECEIPT_QTY", sortable: true, align: "right", renderer: "formatqty", width: 100, filter: { xtype: "textfield" } },
        { header: "SOURCE", dataIndex: "SUMBER_DATA", sortable: true, width: 65, filter: { xtype: "textfield" } },
        { header: "INPUT", dataIndex: "JENIS_INPUT", sortable: true, width: 80, filter: { xtype: "textfield" } },
        { header: "USER", dataIndex: "CREATE_USER", sortable: true, width: 80, filter: { xtype: "textfield" } },
      ],
      bbar: {
        xtype: "pagingtoolbar",
        displayInfo: true,
        displayMsg: "Displaying topics {0} - {1} of {2}",
        emptyMsg: "No topics to display",
      },
    },
  ],
});
