Ext.define("TDK.SYNCHRONIZE.sync_doc_kurir.dokumen_draft.FRMdokumen_draft", {
  extend: "Ext.form.Panel",
  alias: "widget.FRMdokumen_draft",
  reference: "FRMdokumen_draft",
  frame: false,
  border: true,
  autoScroll: true,
  layout: { type: "vbox", pack: "start", align: "stretch" },
  requires: [],
  fieldDefaults: {
    labelAlign: "left",
    labelWidth: 90,
    margin: "0 10 5 0",
  },
  items: [
    {
      xtype: "tabpanel",
      flex: 1,
      tabPosition: "left",
      tabRotation: 0,
      defaults: {
        bodyPadding: 5,
        scrollable: true,
        border: false,
      },
      items: [
        {
          title: "Header Dokumen",
          layout: { type: "vbox", pack: "start", align: "stretch" },
          items: [
            {
              xtype: "container",
              layout: { type: "hbox", pack: "start", align: "stretch" },
              items: [
                {
                  xtype: "fieldset",
                  title: "Dokumen Info",
                  width: 580,
                  items: [
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [
                        { xtype: "textfield", labelWidth: 90, width: 160, fieldLabel: "Pemasok", name: "KODE_INTERNAL", fieldCls: "fieldinput", readOnly: true },
                        { xtype: "textfield", width: 350, name: "NAMA", fieldCls: "fieldinput", readOnly: true },
                        {
                          xtype: "button",
                          pid: "btsearch",
                          vdata: {
                            modulename: "supplier",
                            title: "Pilih Supplier",
                            popupwidth: 0.8,
                            popupheight: 0.7,
                            tofield: { KODE_KANTOR_BONGKAR: "KODE_KANTOR", KODE_KANTOR_BONGKARNAME: "URAIAN_KANTOR" },
                          },
                          icon: vconfig.getstyle + "icon/search.ico",
                          tooltip: "search",
                        },
                      ],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textarea", labelWidth: 90, width: 500, labelAlign: "right", fieldLabel: "Alamat", name: "ALAMAT", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [
                        { xtype: "textfield", labelWidth: 90, width: 150, labelAlign: "right", fieldLabel: "Negara", name: "KODE_NEGARA", fieldCls: "fieldlock", readOnly: true },
                        { xtype: "displayfield", labelWidth: 10, width: 200, name: "NAMA_NEGARA" },
                      ],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [
                        {
                          xtype: "combobox",
                          name: "CBO_BC",
                          fieldLabel: "Dokumen BC",
                          labelWidth: 90,
                          width: 200,
                          displayField: "DEFNAME",
                          valueField: "DEFCODE",
                          fieldCls: "fieldinput",
                          allowBlank: false,
                          queryMode: "local",
                          forceSelection: true,
                          typeAhead: true,
                          minChars: 0,
                          anyMatch: true,
                          value: "23",
                          store: new Ext.data.Store({
                            data: [
                              { DEFCODE: "23", DEFNAME: "23" },
                              { DEFCODE: "23 Kurir", DEFNAME: "23 Kurir" },
                              { DEFCODE: "40", DEFNAME: "40" },
                              { DEFCODE: "261", DEFNAME: "261" },
                            ],
                            fields: ["DEFCODE", "DEFNAME"],
                          }),
                        },
                      ],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [
                        { xtype: "textfield", labelWidth: 90, width: 160, fieldLabel: "KPPBC Bongkar", name: "KODE_KANTOR", fieldCls: "fieldinput", readOnly: true, value: "150300" },
                        {
                          xtype: "button",
                          pid: "btsearch",
                          vdata: {
                            modulename: "kppbcbongkar",
                            title: "Pilih KPPBC Bongkar",
                            popupwidth: 0.4,
                            popupheight: 0.7,
                          },
                          icon: vconfig.getstyle + "icon/search.ico",
                          tooltip: "search",
                          margin: "0 10 0 0",
                        },
                        { xtype: "displayfield", width: 200, name: "KODE_KANTORNAME", readOnly: true, value: "KPPBC TANGERANG" },
                      ],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [
                        { xtype: "textfield", labelWidth: 90, width: 160, fieldLabel: "KPPBC Pengawas", name: "KODE_KANTOR_BONGKAR", fieldCls: "fieldinput", readOnly: true },
                        {
                          xtype: "button",
                          pid: "btsearch",
                          vdata: {
                            modulename: "kppbcpengawas",
                            title: "Pilih KPPBC Pengawas",
                            popupwidth: 0.4,
                            popupheight: 0.7,
                          },
                          icon: vconfig.getstyle + "icon/search.ico",
                          tooltip: "search",
                          margin: "0 10 0 0",
                        },
                        { xtype: "displayfield", width: 200, name: "KODE_KANTOR_BONGKARNAME", readOnly: true },
                      ],
                    },
                  ],
                },
                { xtype: "tbspacer", flex: 1 },
                {
                  xtype: "grid",
                  pid: "GRIDinvoicedata",
                  emptyText: "No Matching Records",
                  autoScroll: true,
                  width: 500,
                  plugins: ["filterfield"],
                  viewConfig: {
                    enableTextSelection: true,
                  },
                  columns: [
                    { xtype: "rownumberer", width: 40 },
                    { header: "KODE", dataIndex: "KODE_JENIS_DOKUMEN", sortable: true, width: 50, filter: { xtype: "textfield" } },
                    { header: "NOMOR", dataIndex: "NOMOR_DOKUMEN", sortable: true, width: 150, filter: { xtype: "textfield" } },
                    { header: "TGL", dataIndex: "TANGGAL_DOKUMEN", sortable: true, width: 80, filter: { xtype: "textfield" } },
                    { header: "URAIAN", dataIndex: "URAIAN_DOKUMEN", sortable: true, flex: 1, filter: { xtype: "textfield" } },
                  ],
                  tbar: ["-", { xtype: "button", pid: "btsearch_invoice", text: "Pilih Invoice", icon: vconfig.getstyle + "icon/search.ico", tooltip: "Pilih Invoice" }],
                },
              ],
            },
            { xtype: "tbspacer", width: 10 },
            {
              xtype: "container",
              layout: { type: "hbox", pack: "start", align: "stretch" },
              items: [
                {
                  xtype: "fieldset",
                  title: "Dokumen Info",
                  width: 560,
                  items: [
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [
                        { xtype: "textfield", labelWidth: 90, width: 150, labelAlign: "right", fieldLabel: "Kode Valuta", name: "KODE_VALUTA", fieldCls: "fieldlock", readOnly: true },
                        { xtype: "displayfield", width: 250, value: "(otomatis terhadap current money invoice)" },
                      ],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "NDPBM", name: "NDPBM", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "FOB", name: "FOB", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "Freight", name: "FOB", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "Asuransi LN/DN", name: "FOB", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "CIF", name: "FOB", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "CIF (Rupiah)", name: "FOB", fieldCls: "fieldlock", readOnly: true }],
                    },
                  ],
                },
                { xtype: "tbspacer", width: 5 },
                {
                  xtype: "fieldset",
                  title: "Khusus untuk BC 23 Kurir & 271",
                  width: 560,
                  items: [
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "Nomor Aju", name: "KODE_VALUTA", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "Tanggal Aju", name: "KODE_VALUTA", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "Nomor Daftar", name: "KODE_VALUTA", fieldCls: "fieldlock", readOnly: true }],
                    },
                    {
                      xtype: "container",
                      layout: "hbox",
                      items: [{ xtype: "textfield", labelWidth: 90, width: 250, labelAlign: "right", fieldLabel: "Tanggal Daftar", name: "NDPBM", fieldCls: "fieldlock", readOnly: true }],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: "Detail Item/Part",
          layout: { type: "vbox", pack: "start", align: "stretch" },
          items: [
            {
              xtype: "grid",
              pid: "GRIDhasilgenerate",
              emptyText: "No Matching Records",
              autoScroll: true,
              flex: 1,
              plugins: ["filterfield"],
              viewConfig: {
                enableTextSelection: true,
              },
              columns: [
                { xtype: "rownumberer", width: 40 },
                { header: "ASURANSI", dataIndex: "ASURANSI", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "CIF", dataIndex: "CIF", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "CIF_RUPIAH", dataIndex: "CIF_RUPIAH", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "DISKON", dataIndex: "DISKON", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "FLAG_KENDARAAN", dataIndex: "FLAG_KENDARAAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "FOB", dataIndex: "FOB", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "FREIGHT", dataIndex: "FREIGHT", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "HARGA_BARANG_LDP", dataIndex: "HARGA_BARANG_LDP", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "HARGA_INVOICE", dataIndex: "HARGA_INVOICE", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "HARGA_PENYERAHAN", dataIndex: "HARGA_PENYERAHAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "HARGA_SATUAN", dataIndex: "HARGA_SATUAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "JENIS_KENDARAAN", dataIndex: "JENIS_KENDARAAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "JUMLAH_BAHAN_BAKU", dataIndex: "JUMLAH_BAHAN_BAKU", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "JUMLAH_KEMASAN", dataIndex: "JUMLAH_KEMASAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "JUMLAH_SATUAN", dataIndex: "JUMLAH_SATUAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KAPASITAS_SILINDER", dataIndex: "KAPASITAS_SILINDER", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KATEGORI_BARANG", dataIndex: "KATEGORI_BARANG", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_ASAL_BARANG", dataIndex: "KODE_ASAL_BARANG", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_BARANG", dataIndex: "KODE_BARANG", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_FASILITAS_DOKUMEN", dataIndex: "KODE_FASILITAS_DOKUMEN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_GUNA", dataIndex: "KODE_GUNA", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_JENIS_NILAI", dataIndex: "KODE_JENIS_NILAI", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_KEMASAN", dataIndex: "KODE_KEMASAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_LEBIH_DARI4TAHUN", dataIndex: "KODE_LEBIH_DARI4TAHUN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_NEGARA_ASAL", dataIndex: "KODE_NEGARA_ASAL", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_SATUAN", dataIndex: "KODE_SATUAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_SKEMA_TARIF", dataIndex: "KODE_SKEMA_TARIF", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_STATUS", dataIndex: "KODE_STATUS", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KONDISI_BARANG", dataIndex: "KONDISI_BARANG", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "MERK", dataIndex: "MERK", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "NETTO", dataIndex: "NETTO", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "NILAI_INCOTERM", dataIndex: "NILAI_INCOTERM", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "NILAI_PABEAN", dataIndex: "NILAI_PABEAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "NOMOR_MESIN", dataIndex: "NOMOR_MESIN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "NOMOR_RANGKA", dataIndex: "NOMOR_RANGKA", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "POS_TARIF", dataIndex: "POS_TARIF", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "SERI_BARANG", dataIndex: "SERI_BARANG", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "SERI_IJIN", dataIndex: "SERI_IJIN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "SERI_POS_TARIF", dataIndex: "SERI_POS_TARIF", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "SPESIFIKASI_LAIN", dataIndex: "SPESIFIKASI_LAIN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "TAHUN_PEMBUATAN", dataIndex: "TAHUN_PEMBUATAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "TIPE", dataIndex: "TIPE", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "UKURAN", dataIndex: "UKURAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "URAIAN", dataIndex: "URAIAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "VOLUME", dataIndex: "VOLUME", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "ID_HEADER", dataIndex: "ID_HEADER", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "ID_EKSPORTIR", dataIndex: "ID_EKSPORTIR", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "NAMA_EKSPORTIR", dataIndex: "NAMA_EKSPORTIR", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "ALAMAT_EKSPORTIR", dataIndex: "ALAMAT_EKSPORTIR", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "KODE_PERHITUNGAN", dataIndex: "KODE_PERHITUNGAN", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "SERI_BARANG_DOK_ASAL", dataIndex: "SERI_BARANG_DOK_ASAL", sortable: true, width: 100, filter: { xtype: "textfield" } },
              ],
              bbar: {
                xtype: "pagingtoolbar",
                displayInfo: true,
                displayMsg: "Total Data {2}",
                emptyMsg: "No topics to display",
              },
              tbar: ["-"],
            },
          ],
        },
        {
          title: "Sumber Data",
          layout: { type: "vbox", pack: "start", align: "stretch" },
          items: [
            {
              xtype: "grid",
              pid: "GRIDsumberdata",
              emptyText: "No Matching Records",
              autoScroll: true,
              flex: 1,
              plugins: ["filterfield"],
              viewConfig: {
                enableTextSelection: true,
              },
              columns: [
                { xtype: "rownumberer", width: 40 },
                { header: "VENDOR", dataIndex: "VENDOR", sortable: true, width: 75, filter: { xtype: "textfield" } },
                { header: "INVOICE", dataIndex: "INVOICE_NO", sortable: true, width: 120, filter: { xtype: "textfield" } },
                { header: "DATE", dataIndex: "INVOICE_DATE", sortable: true, width: 100, filter: { xtype: "textfield" } },
                { header: "TRANSPORT", dataIndex: "TRANSPORT_WAY", sortable: true, width: 80, filter: { xtype: "textfield" } },
                { header: "CARA BAYAR", dataIndex: "CARA_BAYAR", sortable: true, width: 80, filter: { xtype: "textfield" } },
                { header: "ITEM NUMBER", dataIndex: "ITEM_NUMBER", sortable: true, width: 120, filter: { xtype: "textfield" } },
                { header: "ARRIV", dataIndex: "ARRIV_PLAN_NUMBER", sortable: true, width: 80, align: "right", renderer: "formatqty", filter: { xtype: "textfield" } },
                { header: "UOM", dataIndex: "UOM", sortable: true, width: 50, filter: { xtype: "textfield" } },
                { header: "PRICE", dataIndex: "PRICE", sortable: true, width: 80, align: "right", filter: { xtype: "textfield" } },
                { header: "CUR MONEY", dataIndex: "CURRENT_MONEY", sortable: true, width: 50, filter: { xtype: "textfield" } },
                { header: "WEIGHT", dataIndex: "NET_WEIGHT", sortable: true, width: 80, align: "right", renderer: "formatqty", filter: { xtype: "textfield" } },
                { header: "WEIGHT UOM", dataIndex: "WEIGHT_UOM", sortable: true, width: 80, filter: { xtype: "textfield" } },
                { header: "COUNTRY OF", dataIndex: "COUNTRY_OF", sortable: true, width: 80, filter: { xtype: "textfield" } },
                { header: "CAUPRI", dataIndex: "CAUPRI", sortable: true, width: 80, filter: { xtype: "textfield" } },
              ],
              bbar: {
                xtype: "pagingtoolbar",
                displayInfo: true,
                displayMsg: "Total Data {2}",
                emptyMsg: "No topics to display",
              },
              tbar: ["-"],
            },
          ],
        },
      ],
    },
  ],
  dockedItems: [
    {
      xtype: "toolbar",
      height: 30,
      dock: "top",
      items: ["-", { xtype: "button", pid: "btsavedokumendraft", text: "Simpan Dokumen Draft", icon: vconfig.getstyle + "icon/save.ico", tooltip: "Simpan Dokumen Draft" }],
      // other options....
    },
  ],
});
